package ui.component;

import ui.tablerenderer.WonHeaderRenderer;
import java.awt.Color;
import javax.sound.sampled.Clip;

public class SubJPanel extends javax.swing.JPanel {

    private static final String ON = "<html><h4 style='color: #00C957'><b>ON</h4><html>";
    private static final String OFF = "<html><h4 style='color: #DC143C'><b>OFF</h4><html>";
    private static double Dailyalarmranged;
    private static Clip Dailyclip;

    public SubJPanel() {
        initComponents();
        colorRecordTable();
        colorShipNameTable();
    }

    private void colorRecordTable() {
        recordTbl.setShowGrid(true);
        recordTbl.setGridColor(Color.DARK_GRAY);
        recordTbl.getColumnModel().getColumn(0).setHeaderRenderer(new WonHeaderRenderer());
        recordTbl.getColumnModel().getColumn(0).setHeaderValue("<html><b>Available Ship Name Database</b></html>");
    }

    private void colorShipNameTable() {
        shipNameTbl.setShowGrid(true);
        shipNameTbl.setGridColor(Color.DARK_GRAY);
        shipNameTbl.getColumnModel().getColumn(0).setHeaderRenderer(new WonHeaderRenderer());
        shipNameTbl.getColumnModel().getColumn(0).setHeaderValue("<html><b>Available Deflection Records Database</b></html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sliderPanel = new diu.swe.habib.JPanelSlider.JPanelSlider();
        shipDataContainer = new javax.swing.JPanel();
        shipDataTablePanel = new javax.swing.JPanel();
        scrollPaneRight = new javax.swing.JScrollPane();
        shipNameTbl = new javax.swing.JTable();
        shipDataViewPanel = new javax.swing.JPanel();
        deflectionDataContainer = new javax.swing.JPanel();
        deflectionDataTablePanel = new javax.swing.JPanel();
        scrollPaneLeft = new javax.swing.JScrollPane();
        recordTbl = new javax.swing.JTable();
        deflectionDataViewPanel = new javax.swing.JPanel();

        setBorder(null);
        setMaximumSize(new java.awt.Dimension(776, 396));
        setMinimumSize(new java.awt.Dimension(776, 396));
        setPreferredSize(new java.awt.Dimension(776, 396));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        shipDataContainer.setBorder(null);
        shipDataContainer.setPreferredSize(new java.awt.Dimension(780, 405));
        shipDataContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        shipDataTablePanel.setBorder(null);
        shipDataTablePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        shipNameTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Available Ship Name Data"
            }
        ));
        scrollPaneRight.setViewportView(shipNameTbl);

        shipDataTablePanel.add(scrollPaneRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 405));

        shipDataContainer.add(shipDataTablePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 405));

        shipDataViewPanel.setBorder(null);
        shipDataViewPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        shipDataContainer.add(shipDataViewPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 390, 410));

        sliderPanel.add(shipDataContainer, "card4");

        deflectionDataContainer.setBorder(null);
        deflectionDataContainer.setPreferredSize(new java.awt.Dimension(779, 405));
        deflectionDataContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        deflectionDataTablePanel.setBorder(null);
        deflectionDataTablePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        recordTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Available Deflection Records"
            }
        ));
        scrollPaneLeft.setViewportView(recordTbl);

        deflectionDataTablePanel.add(scrollPaneLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 405));

        deflectionDataContainer.add(deflectionDataTablePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 405));

        deflectionDataViewPanel.setBorder(null);
        deflectionDataViewPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        deflectionDataContainer.add(deflectionDataViewPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 380, 400));

        sliderPanel.add(deflectionDataContainer, "card5");

        add(sliderPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 410));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JPanel deflectionDataContainer;
    private javax.swing.JPanel deflectionDataTablePanel;
    private javax.swing.JPanel deflectionDataViewPanel;
    private javax.swing.JTable recordTbl;
    private javax.swing.JScrollPane scrollPaneLeft;
    private javax.swing.JScrollPane scrollPaneRight;
    public static javax.swing.JPanel shipDataContainer;
    private javax.swing.JPanel shipDataTablePanel;
    private javax.swing.JPanel shipDataViewPanel;
    private javax.swing.JTable shipNameTbl;
    public static diu.swe.habib.JPanelSlider.JPanelSlider sliderPanel;
    // End of variables declaration//GEN-END:variables
}
