/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import ui.component.GraphPanel;
import java.util.Map;
import model.DeflectionRecord;
import model.MessageObserver;

public class DeflectionCurve extends javax.swing.JInternalFrame implements MessageObserver {

    private Map<Integer, DeflectionRecord> records;

    public DeflectionCurve(Map<Integer, DeflectionRecord> records) {
        this.records = records;
        // TODO: Add a save as image button.
        initComponents();
    }

    public void setRecords(Map<Integer, DeflectionRecord> records) {
        this.records = records;
    }

    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        deflectionCurvePanel = new GraphPanel(records);

        setTitle("DEFELECTION CURVE");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel.setBackground(new java.awt.Color(122, 206, 224));
        mainPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        mainPanel.setMinimumSize(new java.awt.Dimension(190, 35));
        mainPanel.setPreferredSize(new java.awt.Dimension(190, 35));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(102, 0, 0));
        titleLabel.setText("Deflection Curve");
        mainPanel.add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 240, 30));

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 40));
        getContentPane().add(deflectionCurvePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 1170, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel deflectionCurvePanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update() {
        initComponents();
    }
}
