/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import data.DbConnect;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JTable;
import javax.swing.table.TableModel;
import model.Engine;

/**
 *
 * @author Saminda Permauna
 */
public class OpenRecords extends JDialog {

    private TableModel model;
    private EnterData parent;

    /**
     * Creates new form OpenRecords
     *
     * @param engine
     * @param parent
     */
    public OpenRecords(Engine engine, EnterData parent) {
        this.parent = parent;

        try {
            this.model = DbConnect.getRecordsTabelModel(engine);
            initComponents();
        } catch (Exception ex) {
            Logger.getLogger(OpenRecords.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOpen = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        scrollPaneMain = new javax.swing.JScrollPane();
        tableMain = tableMain = new JTable(model) {
            @Override
            public boolean isCellEditable(int row,int column){
                return false;
            }
        };

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Open Records");
        setAlwaysOnTop(true);
        setName("mainFrame"); // NOI18N
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnOpen.setMnemonic('O');
        btnOpen.setText("Open");
        btnOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenActionPerformed(evt);
            }
        });
        getContentPane().add(btnOpen, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 70, -1));

        btnCancel.setMnemonic('C');
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, -1, -1));

        scrollPaneMain.setViewportView(tableMain);

        getContentPane().add(scrollPaneMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 450, 390));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenActionPerformed
        int row = tableMain.getSelectedRow();

        if (row != -1) {
            Number num = (int) tableMain.getModel().getValueAt(row, 0);
            long headerId = num.longValue();

            parent.setLastSelectedHeaderId(headerId);
            this.dispose();
        }
    }//GEN-LAST:event_btnOpenActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOpen;
    private javax.swing.JScrollPane scrollPaneMain;
    private javax.swing.JTable tableMain;
    // End of variables declaration//GEN-END:variables
}
